//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabase) DeepCopyInto(out *AzureDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabase.
func (in *AzureDatabase) DeepCopy() *AzureDatabase {
	if in == nil {
		return nil
	}
	out := new(AzureDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseExportsSpec) DeepCopyInto(out *AzureDatabaseExportsSpec) {
	*out = *in
	out.DbName = in.DbName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseExportsSpec.
func (in *AzureDatabaseExportsSpec) DeepCopy() *AzureDatabaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseList) DeepCopyInto(out *AzureDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseList.
func (in *AzureDatabaseList) DeepCopy() *AzureDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseSpec) DeepCopyInto(out *AzureDatabaseSpec) {
	*out = *in
	out.SqlServer = in.SqlServer
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureDatabaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	in.ProvisioningMeta.DeepCopyInto(&out.ProvisioningMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseSpec.
func (in *AzureDatabaseSpec) DeepCopy() *AzureDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabase) DeepCopyInto(out *AzureManagedDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabase.
func (in *AzureManagedDatabase) DeepCopy() *AzureManagedDatabase {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureManagedDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseExportsSpec) DeepCopyInto(out *AzureManagedDatabaseExportsSpec) {
	*out = *in
	out.DbName = in.DbName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseExportsSpec.
func (in *AzureManagedDatabaseExportsSpec) DeepCopy() *AzureManagedDatabaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseList) DeepCopyInto(out *AzureManagedDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureManagedDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseList.
func (in *AzureManagedDatabaseList) DeepCopy() *AzureManagedDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureManagedDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseRestoreSpec) DeepCopyInto(out *AzureManagedDatabaseRestoreSpec) {
	*out = *in
	out.StorageContainer = in.StorageContainer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseRestoreSpec.
func (in *AzureManagedDatabaseRestoreSpec) DeepCopy() *AzureManagedDatabaseRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseSpec) DeepCopyInto(out *AzureManagedDatabaseSpec) {
	*out = *in
	out.ManagedInstance = in.ManagedInstance
	out.RestoreFrom = in.RestoreFrom
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureManagedDatabaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	in.ProvisioningMeta.DeepCopyInto(&out.ProvisioningMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseSpec.
func (in *AzureManagedDatabaseSpec) DeepCopy() *AzureManagedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedInstanceSpec) DeepCopyInto(out *AzureManagedInstanceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedInstanceSpec.
func (in *AzureManagedInstanceSpec) DeepCopy() *AzureManagedInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageContainerSpec) DeepCopyInto(out *AzureStorageContainerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageContainerSpec.
func (in *AzureStorageContainerSpec) DeepCopy() *AzureStorageContainerSpec {
	if in == nil {
		return nil
	}
	out := new(AzureStorageContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktop) DeepCopyInto(out *AzureVirtualDesktop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktop.
func (in *AzureVirtualDesktop) DeepCopy() *AzureVirtualDesktop {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVirtualDesktop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktopApplication) DeepCopyInto(out *AzureVirtualDesktopApplication) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktopApplication.
func (in *AzureVirtualDesktopApplication) DeepCopy() *AzureVirtualDesktopApplication {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktopApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktopExportsSpec) DeepCopyInto(out *AzureVirtualDesktopExportsSpec) {
	*out = *in
	out.HostPoolName = in.HostPoolName
	out.ComputerName = in.ComputerName
	out.AdminUserName = in.AdminUserName
	out.AdminPassword = in.AdminPassword
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktopExportsSpec.
func (in *AzureVirtualDesktopExportsSpec) DeepCopy() *AzureVirtualDesktopExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktopExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktopList) DeepCopyInto(out *AzureVirtualDesktopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVirtualDesktop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktopList.
func (in *AzureVirtualDesktopList) DeepCopy() *AzureVirtualDesktopList {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVirtualDesktopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktopSpec) DeepCopyInto(out *AzureVirtualDesktopSpec) {
	*out = *in
	if in.InitScriptArguments != nil {
		in, out := &in.InitScriptArguments, &out.InitScriptArguments
		*out = make([]InitScriptArgs, len(*in))
		copy(*out, *in)
	}
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]AzureVirtualDesktopApplication, len(*in))
		copy(*out, *in)
	}
	in.Users.DeepCopyInto(&out.Users)
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureVirtualDesktopExportsSpec, len(*in))
		copy(*out, *in)
	}
	in.ProvisioningMeta.DeepCopyInto(&out.ProvisioningMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktopSpec.
func (in *AzureVirtualDesktopSpec) DeepCopy() *AzureVirtualDesktopSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualDesktopUsersSpec) DeepCopyInto(out *AzureVirtualDesktopUsersSpec) {
	*out = *in
	if in.Admins != nil {
		in, out := &in.Admins, &out.Admins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationUsers != nil {
		in, out := &in.ApplicationUsers, &out.ApplicationUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualDesktopUsersSpec.
func (in *AzureVirtualDesktopUsersSpec) DeepCopy() *AzureVirtualDesktopUsersSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualDesktopUsersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualMachine) DeepCopyInto(out *AzureVirtualMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualMachine.
func (in *AzureVirtualMachine) DeepCopy() *AzureVirtualMachine {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVirtualMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualMachineExportsSpec) DeepCopyInto(out *AzureVirtualMachineExportsSpec) {
	*out = *in
	out.VmName = in.VmName
	out.ComputerName = in.ComputerName
	out.PublicAddress = in.PublicAddress
	out.AdminUserName = in.AdminUserName
	out.AdminPassword = in.AdminPassword
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualMachineExportsSpec.
func (in *AzureVirtualMachineExportsSpec) DeepCopy() *AzureVirtualMachineExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualMachineExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualMachineList) DeepCopyInto(out *AzureVirtualMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualMachineList.
func (in *AzureVirtualMachineList) DeepCopy() *AzureVirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVirtualMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualMachineSpec) DeepCopyInto(out *AzureVirtualMachineSpec) {
	*out = *in
	in.ProvisioningMeta.DeepCopyInto(&out.ProvisioningMeta)
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureVirtualMachineExportsSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualMachineSpec.
func (in *AzureVirtualMachineSpec) DeepCopy() *AzureVirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapTemplate) DeepCopyInto(out *ConfigMapTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapTemplate.
func (in *ConfigMapTemplate) DeepCopy() *ConfigMapTemplate {
	if in == nil {
		return nil
	}
	out := new(ConfigMapTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRelease) DeepCopyInto(out *HelmRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRelease.
func (in *HelmRelease) DeepCopy() *HelmRelease {
	if in == nil {
		return nil
	}
	out := new(HelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseExportsSpec) DeepCopyInto(out *HelmReleaseExportsSpec) {
	*out = *in
	out.ReleaseName = in.ReleaseName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseExportsSpec.
func (in *HelmReleaseExportsSpec) DeepCopy() *HelmReleaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseList) DeepCopyInto(out *HelmReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseList.
func (in *HelmReleaseList) DeepCopy() *HelmReleaseList {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseSpec) DeepCopyInto(out *HelmReleaseSpec) {
	*out = *in
	in.Release.DeepCopyInto(&out.Release)
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]HelmReleaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	in.ProvisioningMeta.DeepCopyInto(&out.ProvisioningMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseSpec.
func (in *HelmReleaseSpec) DeepCopy() *HelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitScriptArgs) DeepCopyInto(out *InitScriptArgs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitScriptArgs.
func (in *InitScriptArgs) DeepCopy() *InitScriptArgs {
	if in == nil {
		return nil
	}
	out := new(InitScriptArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningMeta) DeepCopyInto(out *ProvisioningMeta) {
	*out = *in
	if in.TenantOverrides != nil {
		in, out := &in.TenantOverrides, &out.TenantOverrides
		*out = make(map[string]*v1.JSON, len(*in))
		for key, val := range *in {
			var outVal *v1.JSON
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(v1.JSON)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningMeta.
func (in *ProvisioningMeta) DeepCopy() *ProvisioningMeta {
	if in == nil {
		return nil
	}
	out := new(ProvisioningMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlServerSpec) DeepCopyInto(out *SqlServerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlServerSpec.
func (in *SqlServerSpec) DeepCopy() *SqlServerSpec {
	if in == nil {
		return nil
	}
	out := new(SqlServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenanantOverridesMeta) DeepCopyInto(out *TenanantOverridesMeta) {
	*out = *in
	if in.TenantOverrides != nil {
		in, out := &in.TenantOverrides, &out.TenantOverrides
		*out = make(map[string]*v1.JSON, len(*in))
		for key, val := range *in {
			var outVal *v1.JSON
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(v1.JSON)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenanantOverridesMeta.
func (in *TenanantOverridesMeta) DeepCopy() *TenanantOverridesMeta {
	if in == nil {
		return nil
	}
	out := new(TenanantOverridesMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueExport) DeepCopyInto(out *ValueExport) {
	*out = *in
	out.ToConfigMap = in.ToConfigMap
	out.ToVault = in.ToVault
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueExport.
func (in *ValueExport) DeepCopy() *ValueExport {
	if in == nil {
		return nil
	}
	out := new(ValueExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSecretTemplate) DeepCopyInto(out *VaultSecretTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSecretTemplate.
func (in *VaultSecretTemplate) DeepCopy() *VaultSecretTemplate {
	if in == nil {
		return nil
	}
	out := new(VaultSecretTemplate)
	in.DeepCopyInto(out)
	return out
}
