//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabase) DeepCopyInto(out *AzureDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabase.
func (in *AzureDatabase) DeepCopy() *AzureDatabase {
	if in == nil {
		return nil
	}
	out := new(AzureDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseExportsSpec) DeepCopyInto(out *AzureDatabaseExportsSpec) {
	*out = *in
	out.DbName = in.DbName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseExportsSpec.
func (in *AzureDatabaseExportsSpec) DeepCopy() *AzureDatabaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseList) DeepCopyInto(out *AzureDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseList.
func (in *AzureDatabaseList) DeepCopy() *AzureDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDatabaseSpec) DeepCopyInto(out *AzureDatabaseSpec) {
	*out = *in
	out.SqlServer = in.SqlServer
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureDatabaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDatabaseSpec.
func (in *AzureDatabaseSpec) DeepCopy() *AzureDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AzureDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabase) DeepCopyInto(out *AzureManagedDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabase.
func (in *AzureManagedDatabase) DeepCopy() *AzureManagedDatabase {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureManagedDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseExportsSpec) DeepCopyInto(out *AzureManagedDatabaseExportsSpec) {
	*out = *in
	out.DbName = in.DbName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseExportsSpec.
func (in *AzureManagedDatabaseExportsSpec) DeepCopy() *AzureManagedDatabaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseList) DeepCopyInto(out *AzureManagedDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureManagedDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseList.
func (in *AzureManagedDatabaseList) DeepCopy() *AzureManagedDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureManagedDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseRestoreSpec) DeepCopyInto(out *AzureManagedDatabaseRestoreSpec) {
	*out = *in
	out.StorageContainer = in.StorageContainer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseRestoreSpec.
func (in *AzureManagedDatabaseRestoreSpec) DeepCopy() *AzureManagedDatabaseRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedDatabaseSpec) DeepCopyInto(out *AzureManagedDatabaseSpec) {
	*out = *in
	out.ManagedInstance = in.ManagedInstance
	out.RestoreFrom = in.RestoreFrom
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]AzureManagedDatabaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedDatabaseSpec.
func (in *AzureManagedDatabaseSpec) DeepCopy() *AzureManagedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureManagedInstanceSpec) DeepCopyInto(out *AzureManagedInstanceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureManagedInstanceSpec.
func (in *AzureManagedInstanceSpec) DeepCopy() *AzureManagedInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(AzureManagedInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageContainerSpec) DeepCopyInto(out *AzureStorageContainerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageContainerSpec.
func (in *AzureStorageContainerSpec) DeepCopy() *AzureStorageContainerSpec {
	if in == nil {
		return nil
	}
	out := new(AzureStorageContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapTemplate) DeepCopyInto(out *ConfigMapTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapTemplate.
func (in *ConfigMapTemplate) DeepCopy() *ConfigMapTemplate {
	if in == nil {
		return nil
	}
	out := new(ConfigMapTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRelease) DeepCopyInto(out *HelmRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRelease.
func (in *HelmRelease) DeepCopy() *HelmRelease {
	if in == nil {
		return nil
	}
	out := new(HelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseExportsSpec) DeepCopyInto(out *HelmReleaseExportsSpec) {
	*out = *in
	out.ReleaseName = in.ReleaseName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseExportsSpec.
func (in *HelmReleaseExportsSpec) DeepCopy() *HelmReleaseExportsSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseExportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseList) DeepCopyInto(out *HelmReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseList.
func (in *HelmReleaseList) DeepCopy() *HelmReleaseList {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseSpec) DeepCopyInto(out *HelmReleaseSpec) {
	*out = *in
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]HelmReleaseExportsSpec, len(*in))
		copy(*out, *in)
	}
	in.Release.DeepCopyInto(&out.Release)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseSpec.
func (in *HelmReleaseSpec) DeepCopy() *HelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlServerSpec) DeepCopyInto(out *SqlServerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlServerSpec.
func (in *SqlServerSpec) DeepCopy() *SqlServerSpec {
	if in == nil {
		return nil
	}
	out := new(SqlServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueExport) DeepCopyInto(out *ValueExport) {
	*out = *in
	out.ToConfigMap = in.ToConfigMap
	out.ToVault = in.ToVault
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueExport.
func (in *ValueExport) DeepCopy() *ValueExport {
	if in == nil {
		return nil
	}
	out := new(ValueExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSecretTemplate) DeepCopyInto(out *VaultSecretTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSecretTemplate.
func (in *VaultSecretTemplate) DeepCopy() *VaultSecretTemplate {
	if in == nil {
		return nil
	}
	out := new(VaultSecretTemplate)
	in.DeepCopyInto(out)
	return out
}
