apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioning-controller
  labels:
    app: provisioning-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioning-controller
  template:
    metadata:
      annotations:
        {{- if .Values.global.rusi.enabled }}
        rusi.io/app-id: Provisioning.Controller
        rusi.io/enabled: "true"
        {{- end }}
      labels:
        app: provisioning-controller
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.global.tag }}
        app.kubernetes.io/managed-by: "helm"
    spec:
      {{- if .Values.global.s3.enabled }}
      volumes:
        - name: provisioner-secrets
          secret:
            secretName: provisioner-secrets
      {{- end }}
      containers:
      - name: provisioning-controller
        image: "{{ .Values.global.registry }}/platform-controllers:{{ .Values.global.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AZURE_ENABLED
          value: {{ .Values.global.azure.enabled | quote }}
        {{- if .Values.global.azure.enabled }}
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: clientSecret
        - name: AZURE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: clientId
        - name: AZURE_LOCATION
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: location
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: subscriptionId
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: tenantId
        - name: AZURE_MANAGED_IDENTITY_RG
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: managedIdentityRG
        - name: AZURE_MANAGED_IDENTITY_NAME
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: managedIdentityName
        - name: ARM_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: clientId 
        - name: ARM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: clientSecret
        - name: ARM_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: tenantId
        {{- end }}
        {{- if eq .Values.global.backend.type "cloud" }}
        - name: PULUMI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: provisioner-secrets
              key: pulumiAccessToken
        {{- else if eq .Values.global.backend.type "custom" }}
        - name: PULUMI_BACKEND_URL
          value: {{ .Values.global.backend.customBackedUrl | quote }}
        - name: PULUMI_CONFIG_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: provisioner-secrets
              key: pulumiConfigPassphrase
        {{- end }}
        - name: VAULT_ENABLED
          value: {{ .Values.global.vault.enabled | quote }}
        {{- if .Values.global.vault.enabled }}
        - name: VAULT_ADDR
          value: "{{ .Values.global.vault.address }}"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name:  provisioner-secrets
              key: vaultAccessToken
        {{- end }}
        {{- if .Values.global.s3.enabled }}
        - name: AWS_PROFILE
          value: "{{ .Values.global.s3.profile }}"
        {{- end }}
        - name: RUSI_ENABLED
          value: "{{ .Values.global.rusi.enabled }}"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name:  provisioner-secrets
              key: githubAccessToken
              optional: true
        {{- if .Values.global.minio.enabled }}
        - name: MINIO_ENDPOINT
          value: "{{ .Values.global.minio.endpoint }}"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name:  provisioner-secrets
              key: minioAccessKey
              optional: true
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name:  provisioner-secrets
              key: minioSecretKey
              optional: true
        {{- end }}
        - name: WORKERS_COUNT
          value: "{{ .Values.global.workersCount }}"
        {{- if .Values.global.s3.enabled }}
        volumeMounts:
          - mountPath: "/home/nonroot/.aws/credentials"
            name: provisioner-secrets
            subPath: s3Credentials
            readOnly: true
        {{- end }}
        command:
        - "/tenant-provisioner"
        args:
        - "--v"
        - "{{ .Values.global.logLevel }}"
      serviceAccountName: provisioning-controller
{{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
{{- end }}