apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioning-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioning-controller-role
rules:
  - apiGroups: ["provisioning.totalsoft.ro"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["batch", "extensions"]
    resources: [ "jobs" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioning-controller-binding
subjects:
  - kind: ServiceAccount
    name: provisioning-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: provisioning-controller-role
  apiGroup: rbac.authorization.k8s.io