global:
  registry: ghcr.io/osstotalsoft/platform-controllers
  tag: "0.0.1"
  imagePullPolicy: IfNotPresent
  imagePullSecrets: "registrykey"
  logLevel: 2
  vault:
    enabled: true
    address: http://vault.vault:8200
